device: 'cuda'
seed: null
output_path: 'results/locomotive_car'
data_path: 'data/locomotive'
latents_path: 'data/locomotive/ddim_latents'
source_prompt: "Amazing quality, masterpiece, A locomotive rides in a forest"
target_prompt: "Amazing quality, masterpiece, A car driving in a forest"
negative_prompt: "bad quality, distortions, unrealistic, distorted image, watermark, signature"
guidance_scale: 10

with_lr_decay: True
optim_lr: 0.01
scale_range: [0.007 , 0.004]
optimization_steps: 10


max_frames: 24
n_timesteps: 50
max_guidance_timestep: 1
min_guidance_timestep: 0.6
features_loss_weight: 0
global_averaging: True
features_diff_loss_weight: 1

restart_sampling: True
random_init: False
high_freq_replacement_init: True
downsample_factor: 4

use_upsampler_features: True
use_temporal_attention_features: True
use_spatial_attention_features: True
use_conv_features: True
use_temp_conv_features: True
up_res_dict: {1: [1]}
guidance_before_res: True
